(() => {
/* Shared portfolio data — projects span all four divisions. */

const PROJECTS = [
  {
    id: "the-fort",
    name: "The Fort Residence",
    category: "Residential",
    year: 2024,
    location: "Fort McMurray, AB",
    client: "Private",
    tone: "warm",
    height: "tall",     // masonry hint
    scope: ["Framing", "Drywall", "Finish Carpentry", "Custom Millwork"],
    desc: "A 4,200 sq ft custom home overlooking the Athabasca, designed for resilience against northern winters and flood-line setbacks. Steel-frame core, triple-pane curtain wall, and a black-clad cedar exterior detailed for the long winter light.",
  },
  {
    id: "northridge-tower",
    name: "Northridge Tower",
    category: "Commercial",
    year: 2023,
    location: "Edmonton, AB",
    client: "Northridge Holdings",
    tone: "cool",
    height: "wide",
    scope: ["Concrete", "Steel Erection", "Curtain Wall", "Tenant Improvements"],
    desc: "A 14-story mixed-use tower anchoring downtown Edmonton's eastern corridor. Ground-floor retail, ten floors of Class-A office, and three residential floors atop. SMG led structural and envelope as design-build partner from concept to occupancy.",
  },
  {
    id: "wildfire-rebuild-1",
    name: "Beacon Hill Rebuild",
    category: "Restoration",
    year: 2017,
    location: "Fort McMurray, AB",
    client: "Insurance Recovery",
    tone: "storm",
    height: "medium",
    scope: ["Demolition", "Foundation Repair", "Full Rebuild", "Landscape"],
    desc: "Among the first homes rebuilt in Beacon Hill following the 2016 Horse River wildfire. Total rebuild from a slab-only condition, including new foundation work, full structural shell, and finishes — delivered in 9 months under insurance scope.",
  },
  {
    id: "smg-headquarters",
    name: "SMG Yard Office",
    category: "Design Build",
    year: 2022,
    location: "Fort McMurray, AB",
    client: "SMG Builders",
    tone: "neutral",
    height: "medium",
    scope: ["Concept", "Permitting", "Concrete", "Steel", "Interiors"],
    desc: "Our own yard, office, and shop on TaigaNova Crescent. A 9,800 sq ft purpose-built facility designed end-to-end by SMG: tilt-up concrete, an industrial-glass storefront, and an interior that doubles as a working showroom for clients.",
  },
  {
    id: "valley-medical",
    name: "Valley Medical Centre",
    category: "Commercial",
    year: 2021,
    location: "Fort McMurray, AB",
    client: "Valley Health Group",
    tone: "warm",
    height: "tall",
    scope: ["Tenant Improvements", "Medical Build-out", "Mechanical", "Finishes"],
    desc: "A 12,000 sq ft tenant improvement transforming a vacant office floor into a multi-disciplinary medical clinic. Eight exam rooms, a procedure suite, and a hardened mechanical package designed around medical-gas and infection-control standards.",
  },
  {
    id: "lakeview-custom",
    name: "Lakeview Custom",
    category: "Residential",
    year: 2024,
    location: "Saprae Creek, AB",
    client: "Private",
    tone: "gold",
    height: "wide",
    scope: ["Design Build", "Foundation", "Full Build", "Finish Carpentry"],
    desc: "A 5,600 sq ft lakefront residence on a wooded acreage. Walk-out basement to grade, a 60-foot-long view wall, and a detached coach-house garage. SMG carried the project from architectural concept through landscape to handover.",
  },
  {
    id: "flood-recovery",
    name: "Downtown Flood Recovery",
    category: "Restoration",
    year: 2020,
    location: "Fort McMurray, AB",
    client: "Multiple Property Owners",
    tone: "storm",
    height: "medium",
    scope: ["Water Mitigation", "Demolition", "Mould Remediation", "Rebuild"],
    desc: "Lead contractor on a portfolio of downtown commercial and residential properties impacted by the 2020 Athabasca flood. Mitigation crews on-site within 48 hours, full rebuild scope delivered across 22 buildings over the following year.",
  },
  {
    id: "industrial-shop",
    name: "Energy Services Shop",
    category: "Commercial",
    year: 2023,
    location: "Fort McMurray, AB",
    client: "Confidential Energy Client",
    tone: "neutral",
    height: "medium",
    scope: ["Pre-Engineered Steel", "Concrete", "Mechanical", "Yard Works"],
    desc: "A 22,000 sq ft pre-engineered steel maintenance shop on a 6-acre yard. 30-tonne overhead cranes, in-ground hoists, and a paint booth meeting Class-A finish standards for heavy-equipment refurbishment.",
  },
  {
    id: "highland-renovation",
    name: "Highland Renovation",
    category: "Residential",
    year: 2024,
    location: "Edmonton, AB",
    client: "Private",
    tone: "warm",
    height: "medium",
    scope: ["Demolition", "Reframing", "Kitchen", "Bath", "Finish"],
    desc: "A whole-home reset of a 1980s split-level. Walls down to studs, structure modified to open the main floor, two bathrooms and a chef's kitchen rebuilt to current finish standards. SMG's Edmonton-side debut.",
  },
  {
    id: "civic-recreation",
    name: "Civic Recreation Annex",
    category: "Design Build",
    year: 2022,
    location: "Wood Buffalo, AB",
    client: "Municipal",
    tone: "cool",
    height: "wide",
    scope: ["Concept", "Permitting", "Structure", "Finishes"],
    desc: "An 8,400 sq ft addition to a regional recreation centre — multipurpose gym, change rooms, and a covered outdoor link to the existing facility. Design-build delivery condensed an 18-month schedule into 11.",
  },
];

window.PortfolioData = { PROJECTS };

})();
